import pyautogui
from time import sleep


print("Bem-vindo ao robo gerador de PDF")

quantidade = int(input("Digite quantos NB existem no sistema (Assim que colocar a quantidade clique no campo do usuario do SCCA): "))
matricula = input("Digite sua Matricula: ")
senha = input("Digite sua Senha: ")

quantidadereal = quantidade - 1

sleep(3)
pyautogui.write('{}'.format(matricula))
sleep(2)
pyautogui.press('tab')
sleep(2)
pyautogui.write('{}'.format(senha))
sleep(2)
pyautogui.press('tab')
sleep(2)
pyautogui.press('enter')
sleep(2)
pyautogui.press('enter')
sleep(2)
pyautogui.press('right')
sleep(2)
pyautogui.hotkey('ctrl', 'c')
sleep(2)
pyautogui.press('f10')
sleep(2)
pyautogui.hotkey('ctrl','v')
sleep(2)
pyautogui.press('enter')
sleep(2)
pyautogui.press('tab')
sleep(2)
pyautogui.press('tab')
sleep(2)
pyautogui.write('{}'.format(matricula))
sleep(2)
pyautogui.press('tab')
sleep(2)
pyautogui.press('enter')
sleep(2)
pyautogui.press('enter')
sleep(2)
pyautogui.press('esc')
sleep(2)

for i in range(quantidadereal):
    pyautogui.press('down')
    sleep(3)
    pyautogui.hotkey('ctrl','c')
    sleep(2)
    pyautogui.press('f10')
    sleep(2)
    pyautogui.hotkey('ctrl', 'v')
    sleep(2)
    pyautogui.press('enter')
    sleep(2)
    pyautogui.press('tab')
    sleep(2)
    pyautogui.press('tab')
    sleep(2)
    pyautogui.write('{}'.format(matricula))
    sleep(2)
    pyautogui.press('tab')
    sleep(2)
    pyautogui.press('enter')
    sleep(2)
    pyautogui.press('enter')
    sleep(2)
    pyautogui.press('esc')
    sleep(2)

